import "./globals.css"
import Header from '../components/header'
import Footer from "../components/footer"
import { ThemeProvider } from 'next-themes';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="ko" suppressHydrationWarning >
      <body>
        <ThemeProvider attribute='class'>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
