import "./globals.css"
import Header from '../components/header'
import Footer from "../components/footer"
import ThemeProviderWrapper from '../components/theme-provider-wrapper'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <ThemeProviderWrapper>
          <Header />
          {children}
          <Footer />
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
